# Generated by Django 4.0.2 on 2023-03-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_movie_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
        migrations.AddField(
            model_name='movie',
            name='publications',
            field=models.ManyToManyField(to='catalog.Genre'),
        ),
    ]
