# Generated by Django 4.0.2 on 2023-03-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_genre_alter_movie_options_alter_movie_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='publications',
            new_name='genre',
        ),
    ]
