# Generated by Django 4.0.2 on 2023-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_person_bio_remove_review_movie_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='catalog.Director'),
        ),
    ]
