# Generated by Django 4.0.2 on 2023-03-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(to='catalog.Writer'),
        ),
    ]
