# Generated by Django 4.0.2 on 2023-04-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_actor_person_remove_director_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review',
        ),
    ]
