# Generated by Django 4.0.2 on 2023-04-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_movie_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.review'),
        ),
    ]
