# Generated by Django 4.0.2 on 2023-05-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(default=' ', upload_to='catalog/img/personality'),
        ),
    ]
