# Generated by Django 4.0.2 on 2023-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_movie_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.TextField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(default=' ', upload_to=''),
        ),
        migrations.AddField(
            model_name='writer',
            name='biography',
            field=models.TextField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='writer',
            name='image',
            field=models.ImageField(default=' ', upload_to=''),
        ),
    ]
