# Generated by Django 4.0.2 on 2023-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
        migrations.AddField(
            model_name='director',
            name='biography',
            field=models.TextField(default=' ', max_length=1000),
        ),
    ]
