# Generated by Django 4.0.2 on 2023-05-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_remove_movie_writer_director_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(to='catalog.Writer'),
        ),
    ]
