# Generated by Django 4.1.7 on 2023-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_actor_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
        migrations.AddField(
            model_name='actor',
            name='biography',
            field=models.TextField(default=' ', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Writer',
        ),
    ]
